/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USBFS_1.h"
#include "USBFS_1_audio.h"
#include "USBFS_1_cdc.h"
#include "USBFS_1_hid.h"
#include "USBFS_1_midi.h"
#include "USBFS_1_pvt.h"
#include "USBFS_1_cydmac.h"
#include "USBFS_1_msc.h"
#include "Clock_1.h"
#include "ButtonReg1.h"
#include "Button_1_8_P0_aliases.h"
#include "Button_1_8_P0.h"
#include "Button_9_16_P2_aliases.h"
#include "Button_9_16_P2.h"
#include "ButtonReg2.h"
#include "Button_17_24_P3_aliases.h"
#include "Button_17_24_P3.h"
#include "ButtonReg3.h"
#include "Button_31_36_P12_aliases.h"
#include "Button_31_36_P12.h"
#include "Button_37_42_P15_aliases.h"
#include "Button_37_42_P15.h"
#include "ButtonReg6.h"
#include "ButtonReg5.h"
#include "Button_25_30_P1_aliases.h"
#include "Button_25_30_P1.h"
#include "ButtonReg4.h"
#include "USBFS_1_Dm_aliases.h"
#include "USBFS_1_Dm.h"
#include "USBFS_1_Dp_aliases.h"
#include "USBFS_1_Dp.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

